### ISSUE TITLE
miss some files

### ISSUE THREAD

**Issue by Un-papasi** [kabirahuja2431/LogoDetection#1]
Hello,I'm learning  your codes.
First,thank you  for your sharing.But I found that the file of data doesn't have the annot_with_bg_train.txt and annot_with_bg_test.txt.It only includes some pictures. Could you provide the .txt files?

**Comment by kabirahuja2431** [comment]
Hi.
I have uploaded the required files, you can access them now.
Thanks

**Comment by Un-papasi** [comment]
Wow,you are so nice!Thank you very much~

**Comment by kabirahuja2431** [comment]
Happy to help :)
